CREATE TABLE IF NOT EXISTS rilevazioni (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   PAESE VARCHAR(100),
   data TIMESTAMP NOT NULL,
   FONTE VARCHAR(4000) NOT NULL,
   VALORE_MW REAL NOT NULL,
   TIPO_BUSINESS CHAR(3),
   UNIQUE(PAESE, data, FONTE)   
);

CREATE TABLE IF NOT EXISTS AREA (
   AREA VARCHAR(25) NOT NULL,
   CODICE VARCHAR(16) NOT NULL PRIMARY KEY,
   DESCRIZIONE VARCHAR(100),
   TIME_ZONE VARCHAR(100) NOT NULL,
   UNIQUE(AREA, CODICE)   
);

CREATE TABLE IF NOT EXISTS FONTE (
   CODICE CHAR(3) NOT NULL PRIMARY KEY,
   DESCRIZIONE VARCHAR(100) NOT NULL,
   UNIQUE(CODICE)
);

CREATE TABLE IF NOT EXISTS TIPO_STATUS (
   CODICE CHAR(3) NOT NULL PRIMARY KEY,
   DESCRIZIONE VARCHAR(100) NOT NULL,
   UNIQUE(CODICE)
);

CREATE TABLE IF NOT EXISTS TIPO_BUSINESS (
   CODICE CHAR(3) NOT NULL PRIMARY KEY,
   DESCRIZIONE VARCHAR(400) NOT NULL,
   UNIQUE(CODICE)
);

CREATE TABLE IF NOT EXISTS TIPO_ACCORDO (
   CODICE CHAR(3) NOT NULL PRIMARY KEY,
   DESCRIZIONE VARCHAR(100) NOT NULL,
   UNIQUE(CODICE)
);

CREATE TABLE IF NOT EXISTS TIPO_DOCUMENTO (
   CODICE CHAR(3) NOT NULL PRIMARY KEY,
   DESCRIZIONE VARCHAR(400) NOT NULL,
   UNIQUE(CODICE)
);

CREATE TABLE IF NOT EXISTS TIPO_PROCESSO (
   CODICE CHAR(3) NOT NULL PRIMARY KEY,
   DESCRIZIONE VARCHAR(400) NOT NULL,
   UNIQUE(CODICE)
);